integrated ML.Net into the API
YVbakker/nots-agls pull request #57
Opened 2022-04-06 08:42 UTC by ThijmenMaus

2022-04-06 12:37 UTC, ilivss approved these changes
Nice

2022-04-06 12:46 UTC, YVbakker requested changes
Nice! Mooi geïntegreerd met de rest van de applicatie, en ziet er goed uit! Twee puntjes van feedback nog, en:
- meeste docs halen we uit swagger, maar voor dit is het denk ik handig om ff een korte instructie in de README te zetten, waar je de tsv kunt vinden (upload die tsv ff in de dataset repo) en hoe je het ml stukje gebruikt, wat het doet in a nutshell
- nu heb ik nog niet kunnen testen, maar als je de tsv ff upload test ik m alsnog even

2022-04-06 12:46 UTC, YVbakker commented on api/Services/MachineLearningService.cs
> +    private static IDataView _trainingDataView;
Als het goed is is `static` hier niet nodig, want we gebruik de service a.d.h.v. DI, als [scoped service](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-6.0#service-lifetimes), waardoor er op een gegeven moment (in een bepaalde scope basically) maar 1 instantie is van deze service.

2022-04-11 12:22 UTC, YVbakker approved these changes
Lijkt me prima zo, ook al gedemo'd. Veel verbeterd sinds de laatste iteratie, en hopelijk een goede basis om evt met ML.NET verder te gaan! Nice 🚀

2022-04-11 12:30 UTC, merged